steps:
  build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet build **/ExtremelySimpleLogger.csproj
  pack:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - find . -type f -name '*.nupkg' -delete
      - dotnet pack **/ExtremelySimpleLogger.csproj --version-suffix ci.$CI_PIPELINE_NUMBER
  push:
    when:
      - event: [push, manual]
        branch: main
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet nuget push -s https://nuget.ellpeck.de/v3/index.json **/*.nupkg -k "$BAGET_KEY" -n true
